name: Lint
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master, release/*]
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS 18.9.0
        uses: actions/setup-node@v2
        with:
          node-version: "18.9.0"
          cache: "npm"
      - name: Install Dependencies
        run: npm install --no-package-lock --no-save prettier prettier-plugin-solidity solhint
      - name: Check Formatting
        run: npm run format:check
      - name: Lint
        run: npm run lint
