name: Test
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master, release/*]
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS 18.9.0
        uses: actions/setup-node@v2
        with:
          node-version: "18.9.0"
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test
